version: '3.1'

services:
  wireguard:
    privileged: false
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    build:
      context: .
    ports:
      - 51820:51820/udp
    secrets:
      - wg0.conf
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

#  wireguard-core:
#    image: linuxserver/wireguard
#    container_name: wireguard
#    cap_add:
#      - NET_ADMIN
#      - SYS_MODULE
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - PEERS=1
#      - PEERDNS="192.168.4.113, 192.168.4.30"
#      - TZ=America/New_York
#    volumes:
#      - ./secrets/wg0.conf:/config/wg0.conf
#      - /lib/modules:/lib/modules
#      - /usr/src:/usr/src
#    ports:
#      - 51820:51820/udp
#    sysctls:
#      - net.ipv4.conf.all.src_valid_mark=1
#    restart: unless-stopped

secrets:
  wg0.conf:
    file: ./secrets/wg0.conf
