version: '3.1'

services:
  wireguard:
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    build:
      context: .
    ports:
      - 51820:51820/udp
    secrets:
      - wg0.conf
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

secrets:
  wg0.conf:
    file: ./secrets/wg0.conf
